### PR TITLE
Made the greeter more customizable

### PR DESCRIPTION
**Pull request by MelihDarcanxyz**
Added ```input-field``` and ```command-selector``` classes to reference in CSS.

### CODE REVIEW

**Comment by MelihDarcanxyz** [comment]
I wonder can the buttons get a similar class name to be customized with CSS

**Comment by yavko** [comment]
This is a mirror, submit a patch on the sourcehut instead

**Comment by kennylevinsen** [comment]
> This is a mirror, submit a patch on the sourcehut instead

Indeed, and that is why I missed it. Unfortunately, Github intentionally makes it impossible for projects to disable pull requests on mirrors, so it's also hard to see.

I'll just merge it here and sync it.

**Comment by kennylevinsen** [comment]
Applied, thanks!

**Pull request merged**
